spring:
  application:
    name: user-center
  profiles:
    active: dev
---
server:
  port: 8082
spring:
  profiles: dev
  datasource:
    #>=6.x com.mysql.cj.jdbc.Driver
    #<=5.x com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    #密码需要用双引号
    password: "#INCLUDE12345"
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 5d1d5b0f-d00a-43f4-8706-901c97ee698f
        #集群划分
        cluster-name: BJ



---
spring:
  profiles: prod
