server:
  port: 9090
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    #>=6.x com.mysql.cj.jdbc.Driver
    #<=5.x com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    #密码需要用双引号
    password: "#INCLUDE12345"
---
spring:
  profiles: prod